# Generated by Django 2.2.24 on 2022-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20220627_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats_owned',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
